// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoIntegradorMVC.Models.ContextoDb;

namespace ProjetoIntegradorMVC.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoIntegradorMVC.Models.DiaDeTrabalho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaDaSemana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JornadaDeTrabalhoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JornadaDeTrabalhoId");

                    b.ToTable("DiaDeTrabalho");
                });

            modelBuilder.Entity("ProjetoIntegradorMVC.Models.HorarioDeTrabalho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Horario")
                        .HasColumnType("datetime2");

                    b.Property<int?>("JornadaDeTrabalhoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JornadaDeTrabalhoId");

                    b.ToTable("HorarioDeTrabalho");
                });

            modelBuilder.Entity("ProjetoIntegradorMVC.Models.JornadaDeTrabalho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("JornadaDeTrabalho");
                });

            modelBuilder.Entity("ProjetoIntegradorMVC.Models.LigaçãoModels.FuncionariosComServicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("ServicoId");

                    b.ToTable("FuncionariosComServicos");
                });

            modelBuilder.Entity("ProjetoIntegradorMVC.Models.Operacoes.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Local")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TempoEstimado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Servico");
                });

            modelBuilder.Entity("ProjetoIntegradorMVC.Models.Usuarios.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("ProjetoIntegradorMVC.Models.Usuarios.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int?>("JornadaDeTrabalhoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("JornadaDeTrabalhoId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("ProjetoIntegradorMVC.Models.DiaDeTrabalho", b =>
                {
                    b.HasOne("ProjetoIntegradorMVC.Models.JornadaDeTrabalho", null)
                        .WithMany("DiasDeTrabalho")
                        .HasForeignKey("JornadaDeTrabalhoId");
                });

            modelBuilder.Entity("ProjetoIntegradorMVC.Models.HorarioDeTrabalho", b =>
                {
                    b.HasOne("ProjetoIntegradorMVC.Models.JornadaDeTrabalho", null)
                        .WithMany("HorariosDeTrabalho")
                        .HasForeignKey("JornadaDeTrabalhoId");
                });

            modelBuilder.Entity("ProjetoIntegradorMVC.Models.LigaçãoModels.FuncionariosComServicos", b =>
                {
                    b.HasOne("ProjetoIntegradorMVC.Models.Usuarios.Empresa", "Empresa")
                        .WithMany("FuncionariosComServicos")
                        .HasForeignKey("EmpresaId");

                    b.HasOne("ProjetoIntegradorMVC.Models.Usuarios.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoIntegradorMVC.Models.Operacoes.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Funcionario");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("ProjetoIntegradorMVC.Models.Operacoes.Servico", b =>
                {
                    b.HasOne("ProjetoIntegradorMVC.Models.Usuarios.Empresa", "Empresa")
                        .WithMany("Servicos")
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ProjetoIntegradorMVC.Models.Usuarios.Empresa", b =>
                {
                    b.OwnsOne("ProjetoIntegradorMVC.Models.EnderecoDaEmpresa", "Endereco", b1 =>
                        {
                            b1.Property<int>("EmpresaId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Bairro")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Bairro");

                            b1.Property<string>("CEP")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CEP");

                            b1.Property<string>("Complemento")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Complemento");

                            b1.Property<string>("Localidade")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Localidade");

                            b1.Property<string>("Logradouro")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Logradouro");

                            b1.Property<string>("UF")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("UF");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("Empresas");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("ProjetoIntegradorMVC.Models.Usuarios.Funcionario", b =>
                {
                    b.HasOne("ProjetoIntegradorMVC.Models.Usuarios.Empresa", "Empresa")
                        .WithMany("Funcionarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoIntegradorMVC.Models.JornadaDeTrabalho", "JornadaDeTrabalho")
                        .WithMany()
                        .HasForeignKey("JornadaDeTrabalhoId");

                    b.Navigation("Empresa");

                    b.Navigation("JornadaDeTrabalho");
                });

            modelBuilder.Entity("ProjetoIntegradorMVC.Models.JornadaDeTrabalho", b =>
                {
                    b.Navigation("DiasDeTrabalho");

                    b.Navigation("HorariosDeTrabalho");
                });

            modelBuilder.Entity("ProjetoIntegradorMVC.Models.Usuarios.Empresa", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("FuncionariosComServicos");

                    b.Navigation("Servicos");
                });
#pragma warning restore 612, 618
        }
    }
}
